version: '3'
services:
 mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --default-authentication-plugin=sha256_password
    # command: "--default-authentication-plugin=mysql_native_password --ignore-db-dir=lost+found --innodb_use_native_aio=0"
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DATABASE_HOST=${DB_HOST} 
      - MYSQL_TCP_PORT=${DB_PORT}
    restart: unless-stopped
    volumes:
      - ./data_mysql:/var/lib/mysql
      - ./db_init/:/docker-entrypoint-initdb.d
    networks:
      - server

# Networks to be created to facilitate communication between containers
networks:
  server:
