apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jobmanager-service
  name: jobmanager-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobmanager-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobmanager-service
    spec:
      automountServiceAccountToken: true
      containers:
      - name: jobmanager-service
        image: registry.atosresearch.eu:18509/orch-scheduler-jobmanager
        imagePullPolicy: Always 
        envFrom:
        - configMapRef:
            name: jobmanager-config
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: nexusetsnsecret
status: {}
